version: '3.8'

services:
  sei-extractor:
    build: .
    container_name: sei-extractor
    environment:
      - SEI_URL=${SEI_URL}
      - SEI_USERNAME=${SEI_USERNAME}
      - SEI_PASSWORD=${SEI_PASSWORD}
      - THREADS=${THREADS}
      - HEADLESS=${HEADLESS}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true